name: Download Models

on:
  workflow_dispatch:  # ให้ workflow ทำงานแบบ manual ได้

jobs:
  download_models:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Create directories
        run: |
          mkdir -p model-cache
          mkdir -p controlnet-cache
          mkdir -p upscaler-cache

      - name: Download ryuzakimixrealistic_v10 model
        run: |
          curl -L -o model-cache/ryuzakimixrealistic_v10.safetensors https://huggingface.co/zenityx/magmix/resolve/main/ryuzakimixrealistic_v10.safetensors

      - name: Download ControlNet control_v11f1e_sd15_tile model
        run: |
          curl -L -o controlnet-cache/control_v11f1e_sd15_tile.pth https://huggingface.co/lllyasviel/ControlNet-v1-1/resolve/main/control_v11f1e_sd15_tile.pth

      - name: Download 4x-ultrasharp upscaler model
        run: |
          curl -L -o upscaler-cache/4x-ultrasharp.pth "https://civitai.com/api/download/models/125843?type=Model&format=PickleTensor"

      - name: Commit and push models
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add model-cache/* controlnet-cache/* upscaler-cache/*
          git commit -m "Add downloaded models"
          git push
